name: pipe-test
home: ""
sources: []
version: ${quarkus.application.version}
description: ""
keywords: []
maintainers: []
icon: ""
apiversion: v2
condition: ""
tags: ""
appversion: ""
deprecated: false
annotations: {}
kubeversion: ""
dependencies:
- name: pipe-test-module
  version: 0.0.0-rc.22
  repository: oci://ghcr.io/andrejpetras/charts
  condition: ""
  tags: []
  enabled: false
  importvalues: []
  alias: app
- name: --helm-deps-version
  version: ""
  repository: ""
  condition: ""
  tags: []
  enabled: false
  importvalues: []
  alias: ""
type: ""
