name: Update helm dependencies

on:
  repository_dispatch:
    types: [update-helm-log]

jobs:
  build:
    name: Update helm dependency
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_PAT }}
          ref: ${{ github.head_ref }}
      - uses: lorislab/install-samo-action@v2
      - name: Update helm chart
        run:
          samo project helm deps-update --helm-absolute-dir --helm-dir helm --helm-deps-name ${{ github.event.client_payload.repo }} --helm-deps-version ${{ github.event.client_payload.version }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(deps): update ${{ github.event.client_payload.repo }} to version ${{ github.event.client_payload.version }}'